# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jack's Blog
paginate:       5
baseurl:        ""
url:            "https://xiongbinzhao.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Xiongbin(Jack) Zhao
  url:
  email:        zxiongbin@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
